name: Auto Switch Base Branch

on:
  pull_request:
    types:
      - opened

jobs:
  switch-base:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Switch base branch
      run: |
        PR_BRANCH=${{ github.head_ref }}
        NEW_BASE=""
        
        if [[ $PR_BRANCH =~ ^feature- ]]; then
          NEW_BASE="develop"
        elif [[ $PR_BRANCH =~ ^RC- ]]; then
          NEW_BASE="master"
        fi

        if [ -n "$NEW_BASE" ]; then
          # Use GitHub API to update the PR's base branch
          gh pr edit ${{ github.event.pull_request.number }} --base $NEW_BASE
        fi
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
