name: Release to Dev Merge
on:
  workflow_dispatch:
jobs:
  MergeReleaseToDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches the entire history for all branches and tags

      - name: Configure Git user
        run: |
          git config --local user.email "30427827+peterjuma@users.noreply.github.com"
          git config --local user.name "peterjuma"

      - name: Merge to Dev
        run: |
          git checkout develop
          git merge release
