name: Simple Workflow with a Failing Job
on: [pull_request]
jobs:
  build_and_test:  # Explicitly named job
    name: Build and Test Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        echo "Building the project..."
        # Build commands go here
    - name: Test
      run: |
        echo "Running tests..."
        # Test commands go here

